[The pages are old and torn, not much can be made out right now]

 ...in the depths, it was said that the right answer was [Option 1]...
...a curse the wizard put on me when I was [wrong]...
...a monster appeared behind me so I....
[The rest is illegible]